name: ExploitFixes
version: 1.0.0
main: eu.kennytv.exploitfixes.ExploitFixesPlugin
author: kennytv
description: Fixes things
website: https://hangar.papermc.io/kennytv/ExploitFixes
api-version: 1.13
folia-supported: true
